spring:
  application:
    name: matchfourinarow

server:
  port: 8080
  servlet:
    context-path: /match-four-in-a-row

logging:
  level:
    me.github.emirhanunsal: DEBUG
    org.springframework.web: INFO
    org.springframework.messaging: DEBUG
